-- Jednotný registr pojišťoven pro výpovědi (zdroj: docs/registry-pojistoven-vypovedi-aidvisora.md)
-- UPSERT globálních řádků (tenant_id IS NULL) podle catalog_key.
-- Neodstraňuje záznamy mimo tento seznam (např. cz:CP, cz:PCS).
-- Po nasazení: registry_needs_verification / registry_internal_notes / last_verified_at se při UPDATE nemění.

INSERT INTO insurer_termination_registry (
  tenant_id, catalog_key, insurer_name, aliases, supported_segments,
  mailing_address, email, data_box, web_form_url, client_portal_url,
  freeform_letter_allowed, requires_official_form,
  official_form_name, official_form_storage_path, official_form_notes,
  allowed_channels, rule_overrides, attachment_rules,
  registry_needs_verification, active
) VALUES

(NULL, 'cz:ALLIANZ', 'Allianz pojišťovna, a.s.',
  '["Allianz","allianz"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Allianz pojišťovna, a.s.","street":"Ke Štvanici 656/3","city":"Praha 8","zip":"186 00","country":"CZ"}'::jsonb,
  'info@allianz.cz', NULL, 'https://www.allianz.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa. Poznámka: Allianz ve FAQ uvádí, že ukončení lze poslat elektronicky nebo poštou na adresu pojišťovny.',
  '["insurer_portal","email","postal_mail","in_person"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:KOOP', 'Kooperativa pojišťovna, a.s., Vienna Insurance Group',
  '["Kooperativa","KOOP","kooperativa","VIG"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Kooperativa pojišťovna, a.s.","street":"Brněnská 634","city":"Modřice","zip":"664 42","country":"CZ"}'::jsonb,
  'info@koop.cz', NULL, 'https://www.koop.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: speciální doručovací / kontaktní adresa (Modřice). Poznámka: Pro doručování a ukončení používá Kooperativa kontaktní adresu v Modřicích, nikoli jen pražské sídlo.',
  '["postal_mail","data_box","insurer_portal","email"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:GENERALI', 'Generali Česká pojišťovna a.s.',
  '["Generali","generali"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Generali Česká pojišťovna a.s.","street":"P.O. Box 305","city":"Brno","zip":"659 05","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.generaliceska.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: speciální doručovací adresa pro dokumenty. Poznámka: Generali na kontaktu výslovně uvádí adresu pro doručení dokumentů.',
  '["postal_mail","data_box","insurer_portal","email"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:CPP', 'Česká podnikatelská pojišťovna, a.s., Vienna Insurance Group',
  '["ČPP","CPP","AXA","axa pojistovna","VIG"]'::jsonb,
  '["MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Česká podnikatelská pojišťovna, a.s.","street":"P.O.BOX 28","city":"Modřice","zip":"664 42","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.cpp.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: speciální korespondenční adresa (Modřice). Poznámka: ČPP rozlišuje centrálu v Praze a korespondenční / klientskou adresu v Modřicích.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:CSOB_POJ', 'ČSOB Pojišťovna, a.s., člen holdingu ČSOB',
  '["ČSOB Pojišťovna","ČSOBP","csob pojistovna"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"ČSOB Pojišťovna, a.s.","street":"Masarykovo náměstí 1458","city":"Pardubice","zip":"530 02","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.csobpoj.cz', NULL,
  true, true, NULL, NULL,
  'Typ adresy: primárně online / formulář; pošta jako fallback (Pardubice). Poznámka: Neživotní pojištění – klientská zóna a online formuláře; životní často přes poradce / pobočku.',
  '["insurer_portal","postal_mail","data_box","in_person"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:UNIQA', 'UNIQA pojišťovna, a.s.',
  '["UNIQA","uniqa","Uniqa"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"UNIQA pojišťovna, a.s.","street":"Úzká 488/8","city":"Brno","zip":"602 02","country":"CZ","department":"Žádosti poštou"}'::jsonb,
  NULL, NULL, 'https://www.uniqa.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: speciální poštovní adresa pro žádosti (Brno). Poznámka: Pro ukončení uvádí poštovní adresu do Brna; sídlo je v Praze 6.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:DIRECT', 'Direct pojišťovna, a.s.',
  '["Direct","direct"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Direct pojišťovna, a.s.","street":"Nové sady 996/25","city":"Brno","zip":"602 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.direct.cz', NULL,
  true, true, NULL, NULL,
  'Typ adresy: primárně online; pošta jako fallback (Brno). Poznámka: Direct nabízí online ukončení; poštovní adresa je záloha.',
  '["insurer_portal","postal_mail","email"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:PILLOW', 'Pillow pojišťovna, a.s.',
  '["Pillow","pillow"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Pillow pojišťovna, a.s.","street":"Tomíčkova 2144/1","city":"Praha 4","zip":"148 00","country":"CZ"}'::jsonb,
  'info@pillow.cz', NULL, 'https://www.pillow.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: primárně e-mail z adresy u smlouvy; pošta možná. Poznámka: Ideálně ukončení přes e-mail z adresy vedené u smlouvy.',
  '["email","postal_mail"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:SLAVIA', 'Slavia pojišťovna a.s.',
  '["Slavia","slavia"]'::jsonb,
  '["MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Slavia pojišťovna a.s.","street":"Táborská 940/31","city":"Praha 4","zip":"140 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.slavia-pojistovna.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa (adresa z formuláře ukončení). Poznámka: U aut může být i online cesta.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:NN', 'NN Životní pojišťovna N.V., pobočka pro Českou republiku',
  '["NN","nn","ING pojistovna"]'::jsonb,
  '["ZP","INV","DIP","DPS","MAJ","ODP"]'::jsonb,
  '{"name":"NN Životní pojišťovna N.V.","street":"Nádražní 344/25","city":"Praha 5","zip":"150 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.nn.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo + online (ePodatelna). Poznámka: NN má online ePodatelnu pro výpověď smlouvy.',
  '["insurer_portal","postal_mail","email"]'::jsonb, '{}'::jsonb, '{"id_copy":"recommended"}'::jsonb,
  true, true),

(NULL, 'cz:METLIFE', 'MetLife Europe d.a.c., pobočka pro Českou republiku',
  '["MetLife","metlife"]'::jsonb,
  '["ZP","INV","DIP","DPS","MAJ"]'::jsonb,
  '{"name":"MetLife Europe d.a.c.","street":"Purkyňova 2121/3","city":"Praha 1","zip":"110 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.metlife.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa. Poznámka: Sídlo v Praze 1; používá se u klientských podání.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:SIMPLEA', 'Simplea pojišťovna, a.s.',
  '["Simplea","simplea"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Simplea pojišťovna, a.s.","street":"Türkova 2319/5b","city":"Praha 4","zip":"149 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.simplea.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa (Chodov). Poznámka: Obecný kontakt na centrálu.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:BNP_CARDIF', 'BNP Paribas Cardif Pojišťovna, a.s.',
  '["Cardif","BNP Paribas Cardif","cardif"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","INV","FIRMA_POJ"]'::jsonb,
  '{"name":"BNP Paribas Cardif Pojišťovna, a.s.","street":"Boudníkova 2506/1","city":"Praha 8","zip":"180 00","country":"CZ","department":"Zákaznický servis"}'::jsonb,
  NULL, NULL, 'https://www.cardif.cz', NULL,
  true, true, NULL, NULL,
  'Typ adresy: primárně online formulář; kontaktní centrum Praha 8. Poznámka: Online formulář i pro ukončení smlouvy.',
  '["insurer_portal","postal_mail","email"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:COLONNADE', 'Colonnade Insurance S.A., organizační složka',
  '["Colonnade","colonnade"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Colonnade Insurance S.A.","street":"Na Pankráci 1683/127","city":"Praha 4","zip":"140 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.colonnade.eu', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa. Poznámka: Pro dokumenty poštou adresa sídla v Praze 4.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:DAS', 'D.A.S. Rechtsschutz AG, pobočka pro ČR',
  '["D.A.S.","DAS","das"]'::jsonb,
  '["ZP","MAJ","ODP","FIRMA_POJ"]'::jsonb,
  '{"name":"D.A.S. Rechtsschutz AG","street":"Vyskočilova 1481/4","city":"Praha 4","zip":"140 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.das.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa (Michle). Poznámka: Výpověď e-mailem, doporučeně poštou i datová schránka.',
  '["email","data_box","postal_mail","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:ERGO_ERV', 'ERGO Cestovní Pojišťovna, a.s. (ERV)',
  '["ERV","ERGO","ergo cestovni"]'::jsonb,
  '["CEST","ZP","MAJ","ODP"]'::jsonb,
  '{"name":"ERGO Cestovní Pojišťovna, a.s.","street":"Křižíkova 237/36a","city":"Praha 8","zip":"186 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.ervpojistovna.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa. Poznámka: Konzistentně uváděná adresa v dokumentech.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:HVP', 'Hasičská vzájemná pojišťovna, a.s.',
  '["HVP","Hasičská","hasicska pojistovna"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"Hasičská vzájemná pojišťovna, a.s.","street":"Římská 2135/45","city":"Praha 2","zip":"120 00","country":"CZ"}'::jsonb,
  'info@hvp.cz', NULL, 'https://www.hvp.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa. Poznámka: Ukončení e-mailem nebo dopisem na tuto adresu.',
  '["email","postal_mail","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:HALALI', 'HALALI, všeobecná pojišťovna, a.s.',
  '["HALALI","halali"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"HALALI, všeobecná pojišťovna, a.s.","street":"Vinohradská 1632/180","city":"Praha 3","zip":"130 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.halali.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / korespondenční adresa. Poznámka: Stejná adresa jako sídlo i korespondenční.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:KOMERCNI_POJ', 'Komerční pojišťovna, a.s.',
  '["Komerční pojišťovna","KB pojišťovna","komercni pojistovna"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","INV","FIRMA_POJ"]'::jsonb,
  '{"name":"Komerční pojišťovna, a.s.","street":"Palackého 53","city":"Jihlava","zip":"586 01","country":"CZ","department":"Změny a ukončení smluv"}'::jsonb,
  NULL, NULL, 'https://www.kb.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: speciální adresa pro podklady (Jihlava). Poznámka: Sídlo v Praze 5; změny a ukončení přes Jihlavu.',
  '["postal_mail","insurer_portal","email","in_person"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:MAXIMA', 'MAXIMA pojišťovna, a.s.',
  '["MAXIMA","maxima"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"MAXIMA pojišťovna, a.s.","street":"Italská 1583/24","city":"Praha 2","zip":"120 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.maxima-pojistovna.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa. Poznámka: Centrála; bez samostatné ukončovací adresy v registru.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:SV_POJ', 'SV pojišťovna a.s.',
  '["SV pojišťovna","SV pojistovna"]'::jsonb,
  '["ZP","MAJ","ODP","AUTO_PR","AUTO_HAV","CEST","FIRMA_POJ"]'::jsonb,
  '{"name":"SV pojišťovna a.s.","street":"Vyskočilova 1481/4","city":"Praha 4","zip":"140 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.svpojistovna.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa. Poznámka: Online klientský servis pro změny a škody.',
  '["insurer_portal","postal_mail","email"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:YOUPLUS', 'YOUPLUS Životní pojišťovna, pobočka pro Českou republiku',
  '["YOUPLUS","youplus"]'::jsonb,
  '["ZP","INV","DIP","DPS","MAJ"]'::jsonb,
  '{"name":"YOUPLUS Životní pojišťovna, pobočka pro Českou republiku","department":"Vlněna Office Park","street":"Přízova 5","city":"Brno","zip":"602 00","country":"CZ"}'::jsonb,
  'info@youplus.cz', NULL, 'https://www.youplus.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: kontaktní adresa (Vlněna Office Park, Brno). Poznámka: V ukončovacím formuláři používá tuto adresu.',
  '["postal_mail","email","insurer_portal"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:AGRA', 'Agra pojišťovna, organizační složka',
  '["Agra","agra pojistovna"]'::jsonb,
  '["ZP","MAJ","FIRMA_POJ"]'::jsonb,
  '{"name":"Agra pojišťovna, organizační složka","street":"Starodejvická 1899/4","city":"Praha 6","zip":"160 00","country":"CZ"}'::jsonb,
  NULL, NULL, 'https://www.agra.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: sídlo / kontaktní adresa. Poznámka: Specializovaná pojišťovna; spíše mimo běžný retail.',
  '["postal_mail","email"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true),

(NULL, 'cz:EGAP', 'Exportní garanční a pojišťovací společnost, a.s. (EGAP)',
  '["EGAP","egap"]'::jsonb,
  '["FIRMA_POJ"]'::jsonb,
  '{"name":"EGAP","street":"P. O. Box 6","city":"Praha 1","zip":"111 21","country":"CZ","department":"Poštovní adresa pro dokumenty"}'::jsonb,
  NULL, NULL, 'https://www.egap.cz', NULL,
  true, false, NULL, NULL,
  'Typ adresy: speciální poštovní adresa (P.O. Box). Poznámka: Exportní / státní; mimo běžný poradenský retail.',
  '["postal_mail","data_box","email"]'::jsonb, '{}'::jsonb, '{}'::jsonb,
  true, true)

ON CONFLICT (catalog_key) WHERE (tenant_id IS NULL)
DO UPDATE SET
  insurer_name = EXCLUDED.insurer_name,
  aliases = EXCLUDED.aliases,
  supported_segments = EXCLUDED.supported_segments,
  mailing_address = EXCLUDED.mailing_address,
  email = EXCLUDED.email,
  data_box = EXCLUDED.data_box,
  web_form_url = EXCLUDED.web_form_url,
  client_portal_url = EXCLUDED.client_portal_url,
  freeform_letter_allowed = EXCLUDED.freeform_letter_allowed,
  requires_official_form = EXCLUDED.requires_official_form,
  official_form_name = EXCLUDED.official_form_name,
  official_form_storage_path = EXCLUDED.official_form_storage_path,
  official_form_notes = EXCLUDED.official_form_notes,
  allowed_channels = EXCLUDED.allowed_channels,
  rule_overrides = EXCLUDED.rule_overrides,
  attachment_rules = EXCLUDED.attachment_rules,
  active = EXCLUDED.active,
  updated_at = now();
